### ISSUE TITLE
Reverse Engineering tools

### ISSUE THREAD

**Issue by aidv** [vjmuzik/Uptown-990-HUI-MCU#1]
Hi!

I'm working on a project just like this. We have a Raindirk Symphony LN2 with Uptown Automation fader system installed.

I am in the process of replacing the old computer with something newer.

Could you share any instructions on how to reverse engineer the protocol?

What signal analyzer did you use? Etc etc..

Kind regards, aidv.

**Comment by vjmuzik** [comment]
What I did was connect the logic analyzer to the output on the ISA cards that run to the de-9 connectors. Any logic analyzer that can recognize the I2C protocol will work just fine for this. 

The protocol itself is fairly simple to reverse engineering, basically I copied the startup sequence and the configuration to put the system in read mode. Then to figure out the messages I just moved each fader and pushed each button separately, noting the changes as I went along. 

If you can make sense of my code it will give you a good jump start into how to get it running. I didn’t copy the full Uptown software, so none of the calibration things are in there though. 

The only thing I did was make it interface with a DAW through the use of either HUI OR MCU midi protocols instead of using the old computer and syncing it through time code.

**Comment by aidv** [comment]
You did everything I was planning to do. You're awesome.
I had a good look at your code and it looks great.
